let findings=[], priority='Acompanhar', inspections=JSON.parse(localStorage.getItem('mda_inspections')||'[]'), maintenance=JSON.parse(localStorage.getItem('mda_maintenance')||'[]');
const $=id=>document.getElementById(id);
function showView(v){document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));$(v).classList.add('active');refresh()}
function setPriority(p){priority=p;$('priorityText').textContent='Classificação selecionada: '+p}
function col(p){return {Alta:'#b91c1c',Programar:'#c2410c',Monitorar:'#a16207',Acompanhar:'#2563eb'}[p]}
function addFinding(){let title=$('findingTitle').value.trim();if(!title)return alert('Informe a constatação.');let f={area:$('area').value,location:$('location').value,title,description:$('description').value,risk:$('risk').value,action:$('action').value,responsible:$('responsible').value,deadline:$('deadline').value,evidence:$('evidence').value,priority};findings.push(f);['location','findingTitle','description','risk','action','responsible','deadline','evidence'].forEach(id=>$(id).value='');renderFindings()}
function renderFindings(){let o=$('findingList');o.innerHTML=findings.map((f,i)=>`<div class="finding" style="border-left-color:${col(f.priority)}"><b>${i+1}. ${f.title}</b> <span class="tag" style="background:${col(f.priority)}">${f.priority}</span><br><small>${f.area} · ${f.location||'Local não informado'}</small><p><b>Risco:</b> ${f.risk||'-'}<br><b>Ação:</b> ${f.action||'-'}<br><b>Responsável:</b> ${f.responsible||'-'}<br><b>Prazo:</b> ${f.deadline||'-'}</p><button class="secondary" onclick="findings.splice(${i},1);renderFindings()">Excluir</button></div>`).join('')||'<p>Nenhuma constatação registrada.</p>'}
function data(){return {id:Date.now(),type:$('type').value,client:$('client').value,property:$('property').value,address:$('address').value,date:$('date').value,inspector:$('inspector').value,contact:$('contact').value,scope:$('scope').value,limitations:$('limitations').value,summary:$('summary').value,findings:[...findings]}}
function saveInspection(){let d=data();if(!d.client||!d.property)return alert('Preencha ao menos Cliente e Imóvel.');inspections.push(d);localStorage.setItem('mda_inspections',JSON.stringify(inspections));refresh();alert('Vistoria salva no dispositivo.')}
function newInspection(){findings=[];document.querySelectorAll('#inspection input:not([type=file]),#inspection textarea').forEach(x=>x.value='');priority='Acompanhar';setPriority(priority);renderFindings()}
function generateReport(id){let d=id?inspections.find(x=>x.id==id):data();$('reportContent').innerHTML=`<div class="report"><h1>RELATÓRIO DE VISTORIA TÉCNICA</h1><p><b>MDA Engenharia</b></p><p><b>Cliente:</b> ${d.client||'-'}<br><b>Imóvel:</b> ${d.property||'-'}<br><b>Endereço:</b> ${d.address||'-'}<br><b>Tipo:</b> ${d.type||'-'}<br><b>Data:</b> ${d.date||'-'}<br><b>Vistoriador:</b> ${d.inspector||'-'}<br><b>Escopo:</b> ${d.scope||'-'}</p><h2>Objetivo e limitações</h2><p>${d.limitations||'-'}</p><h2>Constatações e priorização</h2><table><tr><th>#</th><th>Área / Local</th><th>Constatação</th><th>Risco</th><th>Ação</th><th>Responsável</th><th>Prazo</th><th>Prioridade</th></tr>${d.findings.map((f,i)=>`<tr><td>${i+1}</td><td>${f.area}<br>${f.location||''}</td><td>${f.title}<br><small>${f.description||''}</small></td><td>${f.risk||''}</td><td>${f.action||''}</td><td>${f.responsible||''}</td><td>${f.deadline||''}</td><td><b>${f.priority}</b></td></tr>`).join('')}</table><h2>Plano de ação</h2>${d.findings.map((f,i)=>`<p><b>${i+1}. ${f.title} — ${f.priority}.</b> ${f.action||'Definir ação técnica.'} ${f.responsible?'Responsável: '+f.responsible+'.':''} ${f.deadline?'Prazo: '+f.deadline+'.':''}</p>`).join('')}<h2>Síntese e próximos passos</h2><p>${d.summary||'-'}</p><p><i>Documento operacional. A conclusão técnica, ART/RRT, laudo ou relatório formal devem ser adequados ao escopo e à habilitação profissional aplicáveis.</i></p><div class="actions"><button onclick="window.print()">Imprimir / Salvar PDF</button></div></div>`;$('modal').classList.add('show')}
function closeModal(){$('modal').classList.remove('show')}
function addMaintenance(){let item={id:Date.now(),asset:$('asset').value,frequency:$('frequency').value,responsible:$('maintResponsible').value,nextDate:$('nextDate').value,routine:$('routine').value,evidence:$('maintEvidence').value};if(!item.asset)return alert('Informe o sistema ou ativo.');maintenance.push(item);localStorage.setItem('mda_maintenance',JSON.stringify(maintenance));['asset','frequency','maintResponsible','nextDate','routine','maintEvidence'].forEach(x=>$(x).value='');renderMaintenance()}
function renderMaintenance(){$('maintenanceList').innerHTML=maintenance.map((m,i)=>`<div class="finding"><b>${m.asset}</b><br><small>Periodicidade: ${m.frequency||'-'} · Próxima: ${m.nextDate||'-'} · Responsável: ${m.responsible||'-'}</small><p>${m.routine||''}</p><button class="secondary" onclick="maintenance.splice(${i},1);localStorage.setItem('mda_maintenance',JSON.stringify(maintenance));renderMaintenance()">Excluir</button></div>`).join('')||'<p>Nenhum item cadastrado.</p>'}
function exportData(){let b=new Blob([JSON.stringify(data(),null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='vistoria_MDA.json';a.click()}
function refresh(){let all=inspections.flatMap(x=>x.findings);$('mInspections').textContent=inspections.length;$('mHigh').textContent=all.filter(x=>x.priority==='Alta').length;$('mProgram').textContent=all.filter(x=>x.priority==='Programar').length;$('mMonitor').textContent=all.filter(x=>x.priority==='Monitorar').length;$('mFollow').textContent=all.filter(x=>x.priority==='Acompanhar').length;$('pending').innerHTML=all.filter(x=>x.priority!=='Acompanhar').slice(-10).map(x=>`<div class="finding" style="border-left-color:${col(x.priority)}"><b>${x.title}</b> — ${x.priority}<br><small>${x.action||''}</small></div>`).join('')||'<p>Nenhuma pendência prioritária registrada.</p>';$('inspectionList').innerHTML=inspections.map(x=>`<div class="finding"><b>${x.property}</b> — ${x.type}<br><small>${x.client} · ${x.date||'Sem data'} · ${x.findings.length} constatações</small><p><button onclick="generateReport(${x.id})">Abrir relatório</button></p></div>`).join('')||'<p>Nenhuma vistoria salva.</p>';renderMaintenance()}
renderFindings();refresh();